### ISSUE TITLE
您好.我遇到个问题

### ISSUE THREAD

**Issue by onepve** [quericy/quericy_sign_mail#2]
具体是.第一次安装您的插件.测试发邮件正常.早上报告也是一份.然后我设置其他的时候无意中把插件停止了.于是我就重新开启了他.第二天收到了2分一样的签到邮件.我以为那里设置错误了.就主动把插件停止在启用...现在每天收到3份一样的签到邮件....泪流满面

**Comment by quericy** [comment]
任务执行的日期和上一次计划任务执行到的用户,是由系统的cron控制和调度的

如果你收到的相同的邮件的间隔很短的话,很可能是计划任务的多线程处理问题,插件本身是无法控制系统调度计划任务的.你可以在**全局设置**中将**计划任务线程数**设置为0,以单线程方式运行试试.

如果邮件间隔很长的话,可以尝试修复计划任务状态,或者在插件管理中卸载插件重新安装.

**Comment by onepve** [comment]
感谢您的提醒.确实是多线程问题.我之前设置的2.现在改为0就一封邮件通知了
