### ISSUE TITLE
SAE上不能用

### ISSUE THREAD

**Issue by jlyybz** [quericy/quericy_sign_mail#3]
sae上安了插件不能设置！

**Comment by quericy** [comment]
@jlyybz 麻烦提供一下PHP的日志信息

**Comment by jlyybz** [comment]
已经找到原因，有一处empty()判断在PHP5.3上不支持，迁移到5.6已经解决，谢谢@quericy

**Comment by quericy** [comment]
@jlyybz 感谢反馈，已在代码中修复这个问题。
详见：[https://github.com/quericy/quericy_sign_mail/releases/tag/v1.2.1](https://github.com/quericy/quericy_sign_mail/releases/tag/v1.2.1)
