### ISSUE TITLE
重复发件

### ISSUE THREAD

**Issue by kuilei0926** [quericy/quericy_sign_mail#4]
![qq 20170115111005](https://cloud.githubusercontent.com/assets/17094610/21959978/5bb8b65e-db13-11e6-8297-ddc7d1f57ff3.png)

**Comment by quericy** [comment]
可参考 #2 解决.

duplicate #2 .

**Comment by kuilei0926** [comment]
好的

**Comment by kuilei0926** [comment]
![qq 20170116131751](https://cloud.githubusercontent.com/assets/17094610/21971742/754b09b0-dbee-11e6-90f2-0ebab1f6ee17.png)
改为单线程了还是重复啊

**Comment by quericy** [comment]
@kuilei0926 暂时无法复现这个问题.

如果方便的话,麻烦尽可能提供以下信息(涉及隐私的部分可剔除):
+ 插件的详细执行日志(在 计划任务->quericy_sign_mail->编辑 中,邮箱可打码);

+ 服务器或者云空间环境,执行cron计划任务的方式(crontab还是访问触发或者其他),时间间隔,计划任务线程数,计划任务同时运行是否勾选;

+ 邮件加密方式(TLS还是SSL),使用的哪家的SMTP;

+ 你的发生重复的用户id;

**Comment by kuilei0926** [comment]
![qq 20170116151458](https://cloud.githubusercontent.com/assets/17094610/21973880/95ca530c-dbfe-11e6-8210-68034c65549f.png)

**Comment by kuilei0926** [comment]
![qq 20170116150900](https://cloud.githubusercontent.com/assets/17094610/21973733/be0f05f2-dbfd-11e6-8314-cad78c6d78de.png)
访问触发
计划任务线程数0
计划任务同时运行是否未勾选

**Comment by kuilei0926** [comment]
smtp.ym.163.com

加密方式无

**Comment by kuilei0926** [comment]
一共9个用户，发了19封邮件
![qq 20170116151309](https://cloud.githubusercontent.com/assets/17094610/21973844/5c84580e-dbfe-11e6-88d1-a3480eb3eec6.png)

**Comment by quericy** [comment]
@kuilei0926 感谢提供相关信息.
从截图上来看,更偏向于云签到的系统调度问题.
计划任务的完成耗时3秒,基本是在一次请求内就完成了对所有邮件的发送.
而日志是计入一次php请求的,邮件的表现也是类似并发发送.

如果你是依靠访客触发的计划任务,可能是云签到在多访客同时访问时,任务调度上存在并发问题,插件并不好对这种问题进行加锁的处理.

建议试试改用do.php或do.sh的定时访问来触发(例如利用DNSPod的url监控模式来定期访问do.php的URL).

后续会考虑修改插件在计划任务的部分代码来提升遍历效率.

如果还有后续问题,可以重新开启这个Issue.
