### ISSUE TITLE
测试成功  但是发现一个小bug

### ISSUE THREAD

**Issue by Windman1320** [quericy/quericy_sign_mail#7]
同样得邮件发送了两次

**Comment by quericy** [comment]
可参考 #4 

duplicate #4 .

**Comment by Windman1320** [comment]
好的

**Comment by Windman1320** [comment]
测试发送的时候遇到此问题：
![image](https://cloud.githubusercontent.com/assets/9999486/23056946/cbcbc006-f528-11e6-94ea-db22d2319d94.png)

提示网络异常，但已经成功发送

**Comment by quericy** [comment]
@cappuccinoqi  在提交发送的Ajax请求后进入error方法会提示”网络异常“
这时可能请求发送没有成功，也可能是发送成功但返回数据的时候受到网络等状况的影响
所以会出现发送成功但显示异常的情况

如果一直重现，你可以按F12调出控制台查看下Ajax请求返回的数据包

**Comment by Windman1320** [comment]
前置条件：开启KMMailer的debug，关闭后正常显示
返回结果如下，应该是成功的：
![image](https://cloud.githubusercontent.com/assets/9999486/23058346/802581e4-f52f-11e6-9741-cabdb70d2ef3.png)

**Comment by quericy** [comment]
开启KMMailer是临时的调试方案，这时候返回的数据带有调试输出不是单纯的json，所以只能在控制台查看返回的数据包，web界面里是没法正常显示的。

后续会考虑增加修改debug模式时的返回数据和传输等方式

**Comment by Windman1320** [comment]
好的
